spring:
  application:
    name: zuul-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: zuul-server
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
        ip-address: true
        register: false
server:
  port: 7002
zuul:
  routes:
    api1:
      path: /demo1/**
      serviceId: service-demo1
    api2:
      path: /demo1/**
      serviceId: service-demo2




