spring:
  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 27002
zuul:
  routes:
    api1:
      path: /test1/**
      serviceId: service-demo1
    api2:
      path: /test1/**
      serviceId: service-demo2