spring:
  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 17002
zuul:
  routes:
    api1:
      path: /prd1/**
      serviceId: service-demo1
    api2:
      path: /prd2/**
      serviceId: service-demo2